### ISSUE TITLE
Atualizar repositório com código/dump de produção

### ISSUE THREAD

**Issue by joeljuca** [AssociacaoDrupalBrasil/website#1]
O portal atual, feito pelo Pedro, foi produzido de forma prática, via site building mesmo, e publicado no ar. Nesse momento o código deste repositório não reflete o portal que está disponível online, e precisamos atualizá-lo para que outros desenvolvedores consigam contribuir pro projeto.

Devido à forma que ele foi feito (ver discussões na lista drupal-br) para mais detalhes), será preciso comitar código e banco. Após realizada essa atualização iremos focar em transformar esse setup "developer friendly."

**Comment by handrus** [comment]
Dump e instruções de setup adicionados.
